### ISSUE TITLE
Partition projection: possible alternative to Cloudtrail Partitioner

### ISSUE THREAD

**Issue by aidansteele** [duo-labs/cloudtrail-partitioner#14]
It looks like a week or so ago AWS released [partition projection for Athena](https://docs.aws.amazon.com/athena/latest/ug/partition-projection.html). It discusses the performance benefits (apparently it doesn't need to call the Glue API to list partitions) but I feel the real benefit is avoiding the need to create partitions.

For example, here's how I set it up for my CloudTrail logs:

```
CREATE EXTERNAL TABLE cloudtrail_logs_auto (
	eventversion STRING,
	-- ...trimmed for clarity
	sharedeventid STRING,
	vpcendpointid STRING
)
PARTITIONED BY (accountId string, region string, date string)
ROW FORMAT SERDE 'com.amazon.emr.hive.serde.CloudTrailSerde'
STORED AS INPUTFORMAT 'com.amazon.emr.cloudtrail.CloudTrailInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 's3://bucketname/AWSLogs/o-orgid/'
TBLPROPERTIES(
	"projection.enabled" = "true",
	"projection.date.type" = "date",
	"projection.date.range" = "2020/01/01,NOW",
	"projection.date.format" = "yyyy/MM/dd",
	"projection.date.interval" = "1" ,
	"projection.accountid.type" = "enum",
	"projection.accountid.values" = "0123456789012,210987654321,etc",
	"projection.region.type" = "enum",
	"projection.region.values" = "us-east-1,us-west-2,ap-southeast-2,etc",
	"storage.location.template" = "s3://bucketname/AWSLogs/o-orgid/${accountid}/CloudTrail/${region}/${date}"
);
```

This allows me to run queries like `SELECT * FROM cloudtrail_logs_auto where date >= '2020/02/28' and date < '2020/06/01'`, with or without `accountId` and `region` columns, etc. A few things worth noting:

* You have to enumerate every possible account ID. Account IDs that aren't listed in table properties get ignored. So you'd want to update the table properties when new accounts and added. 
* Likewise, you have to enumerate all regions of interest.
* The `NOW` in `projection.date.range` means "now" in terms of when the query is executed. So new projected partitions automatically appear each day.
* `SHOW partitions cloudtrail_logs_auto` will yield no results

I haven't yet found a gotcha or a reason why *not* to use this new functionality. As long as there aren't any show-stopper issues, it feels like this changes the need for `cloudtrail-partitioner`: it could instead change to keeping the `projection.accountid.values` and `projection.region.values` properties up to date instead. Thoughts?

**Comment by 0xdabbad00** [comment]
Woah, that looks interesting. Due to the requirement to list all of the account id's, it sounds like you'd still want something that runs nightly in order to update that table schema with the list of accounts found in the S3 bucket and also the list of regions (although that is more rare).

Given the name of this project (`cloudtrail-partitioner`), and the large change in functionality, I think it'd be best to create your own project to accomplish this functionality as opposed to this project being modified.

**Comment by m1keil** [comment]
I wish I would read this issue 2 days ago. This is fantastic.

**Comment by 0xdabbad00** [comment]
This is related to #13

**Comment by 0xdabbad00** [comment]
Closing this issue, because with Alex's solution that takes advantage of more recent features of AWS, there isn't a reason to continue improving this project, and this project will only have bug fixes from now on. See https://github.com/alsmola/cloudtrail-parquet-glue

**Comment by KyleKotowick** [comment]
> You have to enumerate every possible account ID. Account IDs that aren't listed in table properties get ignored. So you'd want to update the table properties when new accounts and added.

@aidansteele I understand why this is the case if you're using an `enum` type. If you change it to `"projection.accountid.type" = "integer"` though, would it not consider all accounts listed in that directory?

**Comment by iainelder** [comment]
@0xdabbad00 , I wouldn't normally necromance a closed issue, but I've run into this issue today, and I'm unsure what would be the best solution for a large organization: hundreds of accounts and dozens of gigabytes of new data daily.

Is cloudtrail-parquet-glue still what would you recommend in this situation? It seems to be unmaintained since it was published, so I'm not sure whether to spend effort on working with it.

I tried what @KyleKotowick suggested and was disappointed with Athena's behavior.

> if you change it to "projection.accountid.type" = "integer" though, would it not consider all accounts listed in that directory?

It seems partition projection doesn't work well for sparse values.

You can define the account ID to be an an integer between 0 and 999999999999. But if you don't specify account IDs in your query Athena will just break.

My guess is that Athena doesn't scan the bucket to see which prefixes are actually valid. Instead it just blindly iterates across all integers in the range you define.

I think using an enum to do this would only get you so far. I'm mindful of this limitation in the documentation:

> As a best practice we recommend limiting the use of enum based partition projections to a few dozen or less. Although there is no specific limit for enum projections, the total size of your table’s metadata cannot exceed the AWS Glue limit of about 1MB when gzip compressed. Note that this limit is shared across key parts of your table like column names, location, storage format, and others. If you find yourself using more than a few dozen unique IDs in your enum projection, consider an alternative approach such as bucketing into a smaller number of unique values in a surrogate field. By trading off cardinality, you can control the number of unique values in your enum field.

I haven't found a way to combine the manual partition management for the account IDs with the projection for date ranges.

**Comment by ollytheninja** [comment]
I will also practice some necromancy, since this is one of the top hits when you search the internet for "Athena CloudTrail partition projection".
I couldn't quite copy-pasta Aidan's example above so I've made a gist that works for me (sensitive information removed) https://gist.github.com/ollytheninja/1222d59ca68ce6a896f8a4c77504b5e1
